### ISSUE TITLE
Home Page Layout

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/europehelp.info#21]
I propose to set as home page the English one http://europehelp.info/en/

Any layout improvements?

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
In home page toglierei innanzitutto dal piede riferimento a Covid19 e poi al centro, sotto il nome EuropeInfo.help, metterei _A project to collect and share information to support emergency in Ukraine_
Secondo me non può essere un generico _emergencies_

E poi metterei almeno questi bottoni (su due righe):

1. Segnala
2. Chiedi aiuto
3. Raccolte fondi
4. Accoglienza/ospitalità 
5. Servizi e iniziative solidali 
6. Notizie utili
7. FakeNews
8. Tutte le segnalazioni
 
Infine aggiungerei icona Facebook (con link al gruppo Fb) in basso (dove ci sono Twitter Telegram ecc.) e metterei bene in evidenza (in alto) bandierina Italiana per permettere subito di passare al sito in italiano. Ovviamente se possibile anche altre lingue ma non so se riusciamo a tradurre in più lingue. Intanto almeno italiano e inglese.

**Comment by iltempe** [comment]
@cristigalas 
il piè di pagina è a posto incluso l'icona facebook.
anche il sottotitolo è aggiornato.
i pulsanti ci stiamo lavorando insieme ai form.

**Comment by iltempe** [comment]
chiudo. riapriamo issue specifici rispetto all'home page di oggi.
