### ISSUE TITLE
Modifiche menù in alto 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/europehelp.info#39]
Secondo me per partire è necessario intanto apportare le seguenti modifiche al menù in alto del sito per adattarlo al nuovo progetto Ucraina:

- da _Segui_ togliere _Buone Notizie_ e rinominare voce in _Contatti_ (visto che rimane solo quella)
- in _Partecipa_ aggiungi a _Diventa Contributor_ il testo: oppure inviaci una mail a [indirizzo mail progetto]
- Pagine _Privacy_ una volta aperta ha il titolo _Legal Support_ che è sbagliato. Il titolo è Privacy e qui va inserito un testo per il trattamento dei dati.

Ovviamente le modifiche vanno fatte anche al menu in inglese.

**Comment by iltempe** [comment]
@cristigalas 
primo punto chiuso.
secondo punto non ho capito...dove devo cambiare e come?
terzo punto in realtà nella pagina ci sono sia gli aspetti legali che di privacy. come la chiamiamo?
aspetto tue news!

**Comment by cristigalas** [comment]
@iltempe punto 2 intendo [questa pagina ](https://europehelp.info/credit_form/). Dopo “cliccando qui” aggiungerei di seguito: oppure inviaci una mail a…

Punto 3. La chiamerei allora _Privacy and legal info_

**Comment by iltempe** [comment]
fatto chiudo.
