### ISSUE TITLE
WebForm

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/europehelp.info#8]
Webform templates available ad today. Tool used https://kobo.humanitarianresponse.info/
Lang. English Italian and French.
Suggestions?

<img width="1697" alt="Schermata 2022-02-28 alle 21 03 37" src="https://user-images.githubusercontent.com/6368214/156051145-4321c76f-c3a5-48fc-9b12-9e3ffa533dc9.png">

**Comment by favoeva** [comment]
Eliminerei consegne a domicilio 
Aggiungiamo punti di accoglienza profughi ?

**Comment by cristigalas** [comment]
Concordo con proposta di @favoeva ma metterei solo _Accoglienza profughi_ così può andarci un po’ di tutto sul tema. E poi inserirei anche _Raccolta beni_.

**Comment by cristigalas** [comment]
Ed eventualmente inserirei anche “Offerta alloggi” ([vedi discorso qui](https://github.com/emergenzeHack/europehelp.info/issues/1#issuecomment-1057110435))

**Comment by favoeva** [comment]
Inserire anche “richieste di aiuto”

**Comment by cristigalas** [comment]
@favoeva Non serve , c'è già Chiedi aiuto.

**Comment by Saraveg** [comment]
Accoglienza rifugiati (meglio di profughi)?
Servizi sanitari (vaccini, medici ecc.) 
Servizi per donne
Servizi per minori
Traduzioni

**Comment by iltempe** [comment]
per ora online i form 
chiedi aiuto https://kobo.humanitarianresponse.info/#/forms/a2AV76MYVbtLv5bPm7xifL
segnala contatto https://kobo.humanitarianresponse.info/#/forms/aRaGAzw5qzSwvL7qxp9aaY
segnala raccolta fondi https://kobo.humanitarianresponse.info/#/forms/aHRMxxbCHN7KBfTPywWeev
segnala iniziative e servizi https://kobo.humanitarianresponse.info/#/forms/a823xjxzkHHycU53G47R8V
segnala documenti e dati https://kobo.humanitarianresponse.info/#/forms/amNFA4whpyRw5uxqF4LdnX
segnala fake news https://kobo.humanitarianresponse.info/#/forms/abYFkpxSLuH6Qh2dCzRrNd
segnala notizia https://kobo.humanitarianresponse.info/#/forms/a7veejWys7TzQJsjiwrPfG

sono buoni per inserire i dati e non perderli a questi link ma non sono ancora collegati agli issue di github.

**Comment by cristigalas** [comment]
@iltempe @Saraveg Ho guardato le form. Secondo me ci sono da fare alcune correzioni:

1. in tutte le form campi _nome_ e _email_ sono obbligatori altrimenti diventa difficile eventuale verifica o rintracciamento.
2. Eliminerei le form _Accoglienza_ e _Traduzioni_ e le inserirei nelle opzioni della categoria _Servizi e Iniziative_ (vedi avanti punto 4). Evitiamo troppe form che confondono.
3. La form _Offerta alloggi_ va fatta più simile a quella di Tci aggiungendo email e telefono (email obbligatoria se soggetto è privato). Invece che titolo “Cosa” (che poi diventa titolo issue quando viene inviata alla piattaforma).
4. Nella form _Servizi e Iniziative_ toglierei le varie opzioni riprese da Covid19 e inserirei queste (che poi diventano label):

_- Raccolta/offerta beni
- Accoglienza/ospitalità 
- Trasporto/viaggio
- Assistenza sanitaria
- Assistenza legale
- Mediazione linguistica/traduzioni
- Offerta lavoro
- Aiuto psicologico
- Servizi per bambini 
- Servizi per persone con disabilità 
- Servizi per donne_

Per ora non mi viene in mente altro e grazie a chi ci lavora!

**Comment by iltempe** [comment]
@cristigalas ti rispondo prima di fare qualunque modifica
1 -> siamo sicuri? e se uno vuole lasciare solo mail senza il nome? o viceversa?
2 -> ok si può fare.
3 -> ok ma secondo me mettere nome e telefono obbligatori entrambi non è il massimo
4 -> ok per rimuovere le vecchie iniziative di covid 19...quando dici che diventano label cosa intendi dire? che a mano poi ci mettete la label migliore su github?

**Comment by cristigalas** [comment]
@iltempe Ti rispondo anch'io punto per punto:
1. Secondo me è meglio almeno mail obbligatoria (nome anche no, se credi) perché rende le segnalazioni più verificate e verificabili. Con Tci e Covid19 talvolta abbiamo avuto problemi a rintracciare chi faceva la segnalazioni per chiedere ulteriori info ecc. Con il risultato che le abbiamo dovuto cassare. Ma chiedo lumi anche a @favoeva e chiara.
3. Solo mail obbligatoria se soggetto è privato altrimenti come fanno a contattarli chi ha bisogno di quell'alloggio? 
4. Verrà una label automatica a seconda del servizio selezionato tra le varie opzioni e poi a mano chi l'accetta deve poter aggiungere altre label nel caso la segnalazione sia a cavallo tra categorie diverse oppure sia proprio sbagliata. A volte capita che utente usa form sbagliata o ci aggiunge info che rientrano in altre categorie.

**Comment by chiccap** [comment]
Ciao! Sono d’accordo con @cristigalas almeno la mail è necessaria per poter gestire la issue.

**Comment by favoeva** [comment]
> 1. Secondo me è meglio almeno mail obbligatoria (nome anche no, se credi) perché rende le segnalazioni più verificate e verificabili. Con Tci e Covid19 talvolta abbiamo avuto problemi a rintracciare chi faceva la segnalazioni per chiedere ulteriori info ecc. Con il risultato che le abbiamo dovuto cassare. Ma chiedo lumi anche a @favoeva e @chiccap.

si sono d’accordo con @cristigalas 

anche gli altri punti che solleva sono perfetti 

Aggiungerei servizi per famiglie e/o per anziani

**Comment by Saraveg** [comment]
Ok per il punto 1 di cris e @chiccap  serve un contatto
Unica cosa pensiamo a noi che facciamo inserimenti 'massivi' pescando da social e non solo. Possiamo evitarci passaggi e/o pubblicazione delle mail? Cmq....adelante!

**Comment by iltempe** [comment]
perfetto procedo. adelante @Saraveg ;-)

**Comment by cristigalas** [comment]
> Ok per il punto 1 di cris e @chiccap serve un contatto
> Unica cosa pensiamo a noi che facciamo inserimenti 'massivi' pescando da social e non solo. Possiamo evitarci passaggi e/o pubblicazione delle mail? Cmq....adelante!

@Saraveg @iltempe In questo momento non riesco più ad aprire le form per verificare (non so perché non riesco più ad aprirle, mi dice che c’è un problema 🙄), però per _Fake news, Notizia, Documenti e Dati_ email non serve email, possiamo anche togliere il campo se è stato inserito. Per le altre form è importante mettere email di chi è il soggetto che offre o chiede aiuto, servizi, ecc. Quindi non inseriamo la nostra mail. Non so se mi sono spiegata.

**Comment by iltempe** [comment]
ciao a tutti. abbiamo un problema con i form. dobbiamo capire come procedere e se usare questi. aspettate ad inserire dati.

**Comment by iltempe** [comment]
@Saraveg @cristigalas @chiccap @favoeva aspettate ad usare questi form. purtroppo abbiamo dei problemi ad integrarli sul sito dovuti ad un aggiornamento di KOBO che li rende non usabili. dovremo modificarli. speriamo di fare presto.

**Comment by iltempe** [comment]
chiudo troppo generico. ripartiamo con i form online da oggi. per problemi aprire issue specifici grazie!!!!
