### ISSUE TITLE
Account social

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/europehelp.info#9]
A twitter account is needed?

**Comment by favoeva** [comment]
Apro?

**Comment by iltempe** [comment]
@favoeva go! we don't have any mail...everything is in your hands ;-)

**Comment by favoeva** [comment]
Should gmail address be EuropeHelp.info@ or Ukraineinfo.help@ ?

**Comment by iltempe** [comment]
@favoeva good question. let's take europehelp.info@ like the domain...

**Comment by favoeva** [comment]
Nella bio mettiamo link gruppo Fb e un post fissato in alto con link Telegram per chi vuole contribuire al progetto 
Che ne dite?

**Comment by cristigalas** [comment]
Fatto! Nella bio ci stava anche link a Github.

**Comment by iltempe** [comment]
ok! chiudo? potete mettere il link nell'issue dei canali social? grazie!

**Comment by cristigalas** [comment]
Facebook https://m.facebook.com/groups/449673436901610/
Twitter https://twitter.com/ukraineinfohelp
Telegram https://t.me/ukraineinfohelp

**Comment by cristigalas** [comment]
@iltempe puoi chiudere, grazie! (Semmai prima di chiuderla rinomina issue _account_ _social_ così rimane traccia di tutti gli indirizzi dei profili social).

**Comment by favoeva** [comment]
> Facebook https://m.facebook.com/groups/449673436901610/
> Twitter https://twitter.com/ukraineinfohelp
> Telegram https://t.me/ukraineinfohelp

ho sistemato l’URL del gruppo Fb : ora è 
https://www.facebook.com/groups/ukraineinfo.help

**Comment by favoeva** [comment]
Da valutare account Instagram
