### ISSUE TITLE
Possibilità di embeddare le Form su altri siti

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/europehelp.info#94]
Sarebbe molto utile che in calce alle form ci fosse il boxettino come in Tci "Inserisci il form sul tuo sito"... spingerebbe altri ad usarci o quantomeno ci aiuterebbe nel coinvolgere più persone nelle segnalazioni.

**Comment by iltempe** [comment]
intendi dire sotto ogni form mettere il codice da embeddare?

**Comment by cristigalas** [comment]
> intendi dire sotto ogni form mettere il codice da embeddare?

Si sì, come era in Tci.

**Comment by iltempe** [comment]
questo è chiudibile mi pare no?

**Comment by cristigalas** [comment]
@iltempe Sì sì
